### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by kamyuentse** [alexcrichton/futures-timer#2] opened 2018-01-26 13:56 UTC
command:  `RUSTFLAGS="-C link-dead-code" cargo test -vv --no-run`

```
$ rustc --version
rustc 1.25.0-nightly (da569fa9d 2018-01-16)
$ cargo --version
cargo 0.25.0-nightly (a88fbace4 2017-12-29)
```

log

```
error[E0275]: overflow evaluating the requirement `Inner: std::panic::RefUnwindSafe`
  |
  = help: consider adding a `#![recursion_limit="128"]` attribute to your crate
  = note: required because it appears within the type `alloc::arc::ArcInner<Inner>`
  = note: required because it appears within the type `*const alloc::arc::ArcInner<Inner>`
  = note: required because it appears within the type `core::nonzero::NonZero<*const alloc::arc::ArcInner<Inner>>`
  = note: required because it appears within the type `std::ptr::Shared<alloc::arc::ArcInner<Inner>>`
  = note: required because it appears within the type `std::sync::Weak<Inner>`
  = note: required because it appears within the type `ScheduledTimer`
  = note: required because it appears within the type `std::marker::PhantomData<ScheduledTimer>`
  = note: required because it appears within the type `arc_list::ArcList<ScheduledTimer>`
  = note: required because it appears within the type `Inner`
  = note: required because it appears within the type `alloc::arc::ArcInner<Inner>`
  = note: required because it appears within the type `*const alloc::arc::ArcInner<Inner>`
  = note: required because it appears within the type `core::nonzero::NonZero<*const alloc::arc::ArcInner<Inner>>`
  = note: required because it appears within the type `std::ptr::Shared<alloc::arc::ArcInner<Inner>>`
  = note: required because it appears within the type `std::sync::Weak<Inner>`
  = note: required because it appears within the type `ScheduledTimer`
  = note: required because it appears within the type `std::marker::PhantomData<ScheduledTimer>`
  = note: required because it appears within the type `arc_list::ArcList<ScheduledTimer>`
  = note: required because it appears within the type `Inner`
  = note: required because it appears within the type `alloc::arc::ArcInner<Inner>`
  = note: required because it appears within the type `*const alloc::arc::ArcInner<Inner>`
  = note: required because it appears within the type `core::nonzero::NonZero<*const alloc::arc::ArcInner<Inner>>`
  = note: required because it appears within the type `std::ptr::Shared<alloc::arc::ArcInner<Inner>>`
  = note: required because it appears within the type `std::sync::Weak<Inner>`
  = note: required because it appears within the type `ScheduledTimer`
  = note: required because it appears within the type `std::marker::PhantomData<ScheduledTimer>`
  = note: required because it appears within the type `arc_list::ArcList<ScheduledTimer>`
  = note: required because it appears within the type `Inner`
  = note: required because it appears within the type `alloc::arc::ArcInner<Inner>`
  = note: required because it appears within the type `*const alloc::arc::ArcInner<Inner>`
  = note: required because it appears within the type `core::nonzero::NonZero<*const alloc::arc::ArcInner<Inner>>`
  = note: required because it appears within the type `std::ptr::Shared<alloc::arc::ArcInner<Inner>>`
  = note: required because it appears within the type `std::sync::Weak<Inner>`
  = note: required because it appears within the type `ScheduledTimer`
  = note: required because it appears within the type `std::marker::PhantomData<ScheduledTimer>`
  = note: required because it appears within the type `arc_list::ArcList<ScheduledTimer>`
  = note: required because it appears within the type `Inner`
  = note: required because it appears within the type `alloc::arc::ArcInner<Inner>`
  = note: required because it appears within the type `*const alloc::arc::ArcInner<Inner>`
  = note: required because it appears within the type `core::nonzero::NonZero<*const alloc::arc::ArcInner<Inner>>`
  = note: required because it appears within the type `std::ptr::Shared<alloc::arc::ArcInner<Inner>>`
  = note: required because it appears within the type `std::sync::Weak<Inner>`
  = note: required because it appears within the type `ScheduledTimer`
  = note: required because it appears within the type `std::marker::PhantomData<ScheduledTimer>`
  = note: required because it appears within the type `arc_list::ArcList<ScheduledTimer>`
  = note: required because it appears within the type `Inner`
  = note: required because it appears within the type `alloc::arc::ArcInner<Inner>`
  = note: required because it appears within the type `*const alloc::arc::ArcInner<Inner>`
  = note: required because it appears within the type `core::nonzero::NonZero<*const alloc::arc::ArcInner<Inner>>`
  = note: required because it appears within the type `std::ptr::Shared<alloc::arc::ArcInner<Inner>>`
  = note: required because it appears within the type `std::sync::Weak<Inner>`
  = note: required because it appears within the type `ScheduledTimer`
  = note: required because it appears within the type `std::marker::PhantomData<ScheduledTimer>`
  = note: required because it appears within the type `arc_list::ArcList<ScheduledTimer>`
  = note: required because it appears within the type `Inner`
  = note: required because it appears within the type `alloc::arc::ArcInner<Inner>`
  = note: required because it appears within the type `*const alloc::arc::ArcInner<Inner>`
  = note: required because it appears within the type `core::nonzero::NonZero<*const alloc::arc::ArcInner<Inner>>`
  = note: required because it appears within the type `std::ptr::Shared<alloc::arc::ArcInner<Inner>>`
  = note: required because it appears within the type `std::sync::Weak<Inner>`
  = note: required because it appears within the type `ScheduledTimer`
  = note: required because it appears within the type `arc_list::Node<ScheduledTimer>`
  = note: required because of the requirements on the impl of `std::panic::UnwindSafe` for `std::sync::Arc<arc_list::Node<ScheduledTimer>>`
  = note: required because it appears within the type `std::option::Option<std::sync::Arc<arc_list::Node<ScheduledTimer>>>`
  = note: required because it appears within the type `sleep::Sleep`

error: aborting due to previous error

error: Could not compile `futures-timer`.

Caused by:
  process didn't exit successfully: `rustc --crate-name futures_timer /Users/kam/.cargo/git/checkouts/futures-timer-6c8164b2e0647973/9715aa6/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=8fdf150a955f4a2c -C extra-filename=-8fdf150a955f4a2c --out-dir /Users/kam/Workspace/RustProjects/cswitch/target/debug/deps -L dependency=/Users/kam/Workspace/RustProjects/cswitch/target/debug/deps --extern futures=/Users/kam/Workspace/RustProjects/cswitch/target/debug/deps/libfutures-bcd0e102b4818b5f.rlib --cap-lints warn -C link-dead-code` (exit code: 101)
```

**Comment by alexcrichton** [comment] 2018-01-26 15:17
Thanks for the report! Can you clarify what rev of the repo as well? I'm unable to reproduce...

**Comment by kamyuentse** [comment] 2018-01-26 16:24
@alexcrichton 

I clone the master and run `RUSTFLAGS="-C link-dead-code" cargo test -vv --no-run`, this issue always happen.

Steps:

``` shell
$ git clone https://github.com/alexcrichton/futures-timer.git
$ cd futures-timer && RUSTFLAGS="-C link-dead-code" cargo test -vv --no-run
```

Environment:

```
OS: macOS 10.13.2 kernel: Darwin Kernel Version 17.3.0
rustc: 1.25.0-nightly (da569fa9d 2018-01-16)
cargo: 0.25.0-nightly (a88fbace4 2017-12-29)
```

```
OS: Ubuntu 14.04.1  kernel: 3.13.0-141-generic
rustc: 1.25.0-nightly (9fd7da904 2018-01-25)
cargo: 0.26.0-nightly (91e36aa86 2018-01-25)
```

**Comment by alexcrichton** [comment] 2018-01-26 19:28
Hm weird, the `RUSTFLAGS` is necessary to generate the error, only I'm not sure why...

This looks like a rustc bug though? I'm not sure what we could do to trigger this... [This](https://gist.github.com/1620c5b9bded982dc3ce376910729795) is as small as I've gotten it so far though.

**Comment by kamyuentse** [comment] 2018-01-27 01:34
Thanks for your time.
I found some reports related to `-Clink-dead-code`(https://github.com/rust-lang/rust/issues/45629) , but I am not familiar with the `rustc` internal, I don't know what I can do for this.

**Comment by alexcrichton** [comment] 2018-01-29 15:02
Ah ok I don't think that's precisely the same issue (but maybe related?).

The best way to make progress on this I think is to make a digestable test case that can be reported to upstream rust-lang/rust. Unfortunately there's a few too many dependencies here and the failure isn't isolated enough, but if we were able to get it to a smaller state then it may be fixable upstream!

**Comment by rubdos** [comment] 2018-02-24 10:24
I've got this too when running my project against tarpaulin, the coverage tool. More specifically, on the `xd009642/tarpaulin:develop-nightly` Docker image in GitLab CI.

I have no clue whether this statement may help you find what the problem is, but don't hesitate to ask me for more data... if you remotely know where I should look.

**Comment by alexcrichton** [comment] 2018-02-24 19:52
@rubdos oh this is unfortunately not an issue in this crate I believe but rather an upstream rust-lang/rust issue. I think the closest issue is https://github.com/rust-lang/rust/issues/45629, so I'm going to close this in favor of that.

**Closed by alexcrichton** 2018-02-24 19:52 UTC
